# Generated by Django 5.2 on 2026-10-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simbaapp', '0007_activity_llm_model_together'),
        ('simbaapp', '0008_alter_activity_ai_model'),
    ]

    operations = [
    ]
