# Generated by Django 5.2 on 2026-10-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simbaapp', '0009_merge_20261008_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ai_model',
            field=models.CharField(choices=[('gpt', 'GPT'), ('mistral', 'Mistral'), ('together', 'Together AI')], default='mistral', max_length=20),
        ),
    ]
